### ISSUE TITLE
config.yml uses undefined variable nextcloud_config

### ISSUE THREAD

**Issue by Duckle29** [nkakouros-original/ansible-role-nextcloud#20]
The only other place that variable is mention is in the molecule playbook, and as such won't be missing when running tests through molecule.

**Comment by nkakouros** [comment]
You are right, thanks for noticing this. Actually, in the past I was using two variables `nextcloud_config_system` and `nextcloud_config_global` but later I combined them into a single `nextcloud_config`. It worked on my server and left updating the docs/comments/etc for another day. I added a mention of `nextlcoud_config` in the `README.md` now, but I should make it even clearer. When I have some time, I will revisit it.

**Comment by nkakouros** [comment]
I think this is ok now.
