### ISSUE TITLE
Issue with nextcloud_config comparison

### ISSUE THREAD

**Issue by simonspa** [nkakouros-original/ansible-role-nextcloud#31]
For me, the update of the configuration file with items from `nextcloud_config` does not work as expected - the local variable content just never ends up on the machine. What is currently happening is:

* fetch config dict from instance
* get dict from `nextcloud_config` key
* Do comparison of flattened dicts, skip all if `nextcloud_config <= global_config`.

There are two issues I believe:
* we might need to call `occ config::list --private` to also get the database passwords etc, otherwise these are just `**REMOVED SENSITIVE VALUE**` entries
* Alternatively we could only compare if keys exist, but this would not catch a change in a parameter.
* merge the two dicts and compare the result against the one from the instance to see if there was a change, and then invoke the `occ import` command with the provided configuration.

What do you think? Does this make sense? Or is this working for you?

**Comment by nkakouros** [comment]
Nice catch. I think the 3rd option is the best. Let me take a look at it.
